#ifndef RADIO_INFO_H
#define RADIO_INFO_H

enum {
	RADIO_TIMESYNC_MSG = 200,
	RADIO_JOIN_REQ_MSG = 201,
	RADIO_JOIN_ANS_MSG = 202,
	RADIO_DATA_PKG_MSG = 203,
	RADIO_ASSIGNMENT_MSG = 204
};

#endif /* RADIO_INFO_H */
